[mount]
[[mount.databases]]
    database_id = "b7b1816c05ec464391c8c111fa242985"
    target_folder = "posts"
[[mount.pages]]
    page_id = "45eb121158b9489480ec000fd25c812b"
    target_folder = "."

[formatter]
[formatter.equation]
    # config how maths equations are rendered into markdown
    # there are three options (markdown, shortcode, ssr)
    # the markdown option renders the equations in default markdown flavor:
    #    \(inline equation\) \[displayed equation\]
    # the shortcode option renders the equations into the math shortcode 
    #    which relies on your Hugo theme to support and render the equations
    # the ssr option directly renders equations into HTML + MathML
    #    when converting your Notion page into the markdown file, 
    #    it makes the markdown file a lot less readable but it works for all themes. 
    #    `markup.goldmark.renderer.unsafe` needs to be set to true for the HTML tags to work,
    #    which is the default setting.
    #    https://gohugo.io/getting-started/configuration-markup/#configure-markup
    style = "ssr"